name = "MinkaExampleErrorInVariables"
uuid = "753e9f2e-178b-4068-88c3-bc9d9e9fe4d1"
authors = ["Nikos Gianniotis"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
